import { after, before, describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { authenticatedFetch, postJson, startTestServer } from './httpTestUtils.ts';
import type { TestServer } from './httpTestUtils.ts';

describe('profiles, social links, friends, and messages', () => {
  let ctx: TestServer; before(async () => { ctx = startTestServer(); await ctx.ready; }); after(() => ctx.close());
  it('isolates profiles and validates social usernames and visibility', async () => { assert.equal((await authenticatedFetch(ctx, 'mallory', '/riders/alice/profile')).status, 403); const updated = await authenticatedFetch(ctx, 'alice', '/riders/alice/profile', { method: 'PUT', body: JSON.stringify({ instagramUsername: 'ali.rides', instagramVisibility: 'public', tiktokUsername: 'ali_rides', tiktokVisibility: 'friends' }) }); assert.equal(updated.status, 200); const profile = await updated.json() as { instagramUsername: string; tiktokVisibility: string }; assert.equal(profile.instagramUsername, 'ali.rides'); assert.equal(profile.tiktokVisibility, 'friends'); assert.equal((await authenticatedFetch(ctx, 'alice', '/riders/alice/profile', { method: 'PUT', body: JSON.stringify({ instagramVisibility: 'everyone' }) })).status, 400); });
  it('enforces social visibility when another rider views a profile', async () => { ctx.authStore.createTestSession('alice'); ctx.authStore.createTestSession('viewer'); ctx.profileStore.update('alice', { instagramUsername: 'ali.rides', instagramVisibility: 'public', tiktokUsername: 'secret', tiktokVisibility: 'private' }); const res = await authenticatedFetch(ctx, 'viewer', '/profiles/alice'); const profile = await res.json() as { instagramUsername: string; tiktokUsername: string }; assert.equal(profile.instagramUsername, 'ali.rides'); assert.equal(profile.tiktokUsername, ''); });
  it('derives request and message senders from authentication', async () => { ctx.authStore.createTestSession('bob'); const made = await postJson(ctx, 'alice', '/friends/requests', { toRiderId: 'bob', fromRiderId: 'mallory' }); const request = await made.json() as { id: string; fromRiderId: string }; assert.equal(request.fromRiderId, 'alice'); assert.equal((await postJson(ctx, 'bob', `/friends/requests/${request.id}/accept`, {})).status, 200); const sent = await postJson(ctx, 'alice', '/messages', { toRiderId: 'bob', text: ' hello ' }); const message = await sent.json() as { fromRiderId: string; text: string }; assert.deepEqual(message, { ...message, fromRiderId: 'alice', text: 'hello' }); });
});
