import { StyleSheet } from 'react-native';
import { colors, spacing, radii, type, elevation, MIN_TOUCH_TARGET } from '../theme';

export const styles = StyleSheet.create({
  bar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    minHeight: 48,
    backgroundColor: colors.surfaceRaised,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.lg,
    paddingHorizontal: spacing.md,
    marginHorizontal: spacing.lg,
    marginBottom: spacing.sm,
    ...elevation.raised,
  },
  barPressed: { opacity: 0.85 },
  barText: { ...type.body, color: colors.textPrimary, flex: 1 },
  speakerPill: {
    maxWidth: 160, flexDirection: 'row', alignItems: 'center', gap: 4,
    paddingHorizontal: 7, paddingVertical: 4, borderRadius: radii.pill,
    backgroundColor: colors.surface,
  },
  speakerPillText: { ...type.caption, color: colors.accent, fontWeight: '800', flexShrink: 1 },
  locationLivePill: {
    flexDirection: 'row', alignItems: 'center', gap: 3,
    paddingHorizontal: 7, paddingVertical: 4, borderRadius: radii.pill,
    backgroundColor: colors.surface,
  },
  locationLiveText: { ...type.caption, color: colors.success, fontWeight: '800' },
  liveDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: colors.success },
  errorDot: { backgroundColor: colors.danger },
  voiceStatusText: { ...type.caption, color: colors.textSecondary },
  lockedBar: {
    flexDirection: 'row', alignItems: 'center', gap: spacing.sm,
    minHeight: 58, backgroundColor: colors.surfaceRaised,
    borderWidth: 1, borderColor: colors.border, borderRadius: radii.lg,
    paddingHorizontal: spacing.md, marginHorizontal: spacing.lg, marginBottom: spacing.sm,
    ...elevation.raised,
  },
  lockedBarCopy: { flex: 1, minWidth: 0 },
  compactLeaveButton: {
    minHeight: MIN_TOUCH_TARGET, flexDirection: 'row', alignItems: 'center', gap: spacing.xs,
    paddingHorizontal: spacing.sm, borderRadius: radii.md,
    borderWidth: 1, borderColor: colors.danger,
  },
  compactLeaveText: { ...type.caption, color: colors.danger, fontWeight: '800' },
  sheet: { flex: 1, backgroundColor: colors.background, padding: spacing.lg, gap: spacing.md },
  sheetHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  closeButton: { padding: spacing.xs },
  statusRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  statusText: { ...type.label, color: colors.success },
  codeCard: {
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    padding: spacing.md,
    alignItems: 'center',
    ...elevation.raised,
  },
  codeCardHead: { width: '100%', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  codeCardActions: { flexDirection: 'row', gap: spacing.xs },
  codeCardAction: { width: 30, height: 30, borderRadius: radii.md, alignItems: 'center', justifyContent: 'center' },
  codeLabel: { ...type.caption },
  codeValue: { fontSize: 32, fontWeight: '800', letterSpacing: 6, color: colors.accent, marginTop: spacing.xs },
  rideId: { ...type.caption },
  voiceError: { ...type.caption, color: colors.danger },
  locationCard: {
    flexDirection: 'row', alignItems: 'center', gap: spacing.md,
    backgroundColor: colors.surface, padding: spacing.md, borderRadius: radii.lg,
    borderWidth: 1, borderColor: colors.border,
  },
  locationCardCopy: { flex: 1 },
  locationCardTitle: { ...type.label, color: colors.textPrimary },
  locationCardBody: { ...type.caption, color: colors.textSecondary, marginTop: 3, lineHeight: 18 },
  locationSwitch: {
    width: 50, height: 30, borderRadius: 15, padding: 3,
    justifyContent: 'center', backgroundColor: colors.surfaceRaised,
    borderWidth: 1, borderColor: colors.border,
  },
  locationSwitchOn: { backgroundColor: colors.accent, borderColor: colors.accent },
  locationSwitchKnob: { width: 22, height: 22, borderRadius: 11, backgroundColor: colors.textMuted },
  locationSwitchKnobOn: { alignSelf: 'flex-end', backgroundColor: colors.accentText },
  mixerCard: { backgroundColor: colors.surface, padding: spacing.md, borderRadius: radii.lg, gap: spacing.md },
  mixerLabel: { ...type.caption, marginBottom: spacing.xs },
  gainRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  gainIcon: { width: 18 },
  gainLabel: { ...type.body, color: colors.textPrimary, width: 90 },
  gainTrack: { flex: 1, height: 8, borderRadius: radii.pill, backgroundColor: colors.border, overflow: 'hidden' },
  gainFill: { height: '100%', backgroundColor: colors.accent, borderRadius: radii.pill },
  talkButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    minHeight: MIN_TOUCH_TARGET,
    backgroundColor: colors.surfaceRaised,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.lg,
    marginTop: 'auto',
  },
  talkButtonActive: { backgroundColor: colors.accent, borderColor: colors.accent },
  talkButtonPressed: { opacity: 0.85 },
  talkButtonText: { ...type.button, color: colors.textPrimary },
  leaveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    minHeight: MIN_TOUCH_TARGET,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.danger,
  },
  leaveButtonPressed: { backgroundColor: colors.dangerSurface },
  leaveButtonText: { ...type.button, color: colors.danger },
});
