import { StyleSheet } from 'react-native';
import { colors, MIN_TOUCH_TARGET, radii, spacing, type } from '../theme';

export const styles = StyleSheet.create({
  cardGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 },
  curatedCard: { height: 138, overflow: 'hidden', borderRadius: radii.md, backgroundColor: colors.surface, borderWidth: StyleSheet.hairlineWidth, borderColor: colors.border },
  cardPressed: { opacity: 0.88, transform: [{ scale: 0.99 }] },
  cardMedia: { position: 'relative', height: 78, backgroundColor: colors.surfaceRaised },
  cardImage: { width: '100%', height: '100%' },
  cardImageShade: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, backgroundColor: 'rgba(5,8,11,0.10)' },
  imageFallback: { alignItems: 'center', justifyContent: 'center' },
  routeTrace: { borderRadius: radii.sm, backgroundColor: 'rgba(8,10,16,0.72)', overflow: 'hidden' },
  cardBody: { flex: 1, justifyContent: 'center', paddingHorizontal: spacing.sm, paddingVertical: spacing.xs, backgroundColor: colors.surface },
  cardTitle: { ...type.subheading, color: colors.textPrimary, fontSize: 14, lineHeight: 17, fontWeight: '800' },
  cardRegion: { ...type.caption, color: colors.textSecondary, marginTop: 0, fontSize: 10 },
  cardStats: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 4 },
  cardStatItem: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  cardStat: { ...type.caption, color: colors.textMuted, fontSize: 10, fontWeight: '700', textTransform: 'capitalize' },
  overviewRoot: { flex: 1, backgroundColor: colors.background },
  overviewScroll: { backgroundColor: colors.background },
  overviewHero: { height: 300, justifyContent: 'flex-end' },
  overviewImage: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, width: '100%', height: '100%' },
  overviewImageFallback: { alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surfaceRaised },
  overviewShade: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, backgroundColor: 'rgba(4,7,10,0.42)' },
  closeButton: { position: 'absolute', right: spacing.md, width: MIN_TOUCH_TARGET, height: MIN_TOUCH_TARGET, borderRadius: radii.sm, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(11,15,20,0.82)' },
  heroCopy: { padding: spacing.lg, gap: spacing.xs },
  heroRegion: { ...type.label, color: colors.accent, fontWeight: '800', letterSpacing: 1.1, textTransform: 'uppercase' },
  heroTitle: { ...type.title, color: '#FFFFFF' },
  heroRoad: { ...type.body, color: '#FFFFFF', fontWeight: '700' },
  overviewBody: { width: '100%', maxWidth: 720, alignSelf: 'center', padding: spacing.lg, gap: spacing.lg },
  metaStrip: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, padding: spacing.md, borderRadius: radii.md, backgroundColor: colors.surface },
  metaItem: { minWidth: 95, flex: 1, flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  metaValue: { ...type.label, color: colors.textPrimary, textTransform: 'capitalize' },
  metaLabel: { ...type.caption, color: colors.textMuted },
  tracePanel: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.md, padding: spacing.md, borderRadius: radii.md, backgroundColor: colors.surface },
  traceCopy: { flex: 1, gap: 3 },
  traceText: { ...type.body, color: colors.textPrimary, fontWeight: '700' },
  traceTextMuted: { ...type.caption, color: colors.textSecondary },
  overviewDescription: { ...type.body, color: colors.textPrimary, fontSize: 17, lineHeight: 25 },
  riderNote: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.md, padding: spacing.md, borderRadius: radii.md, backgroundColor: colors.surface },
  riderNoteText: { ...type.body, color: colors.textSecondary, flex: 1 },
  sectionTitle: { ...type.subheading, color: colors.textPrimary },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs },
  highlightTag: { paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderRadius: radii.sm, backgroundColor: colors.surfaceRaised },
  highlightText: { ...type.caption, color: colors.textPrimary, fontWeight: '700', textTransform: 'capitalize' },
  noticeList: { gap: spacing.sm },
  noticeRow: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm },
  noticeText: { ...type.body, color: colors.textSecondary, flex: 1 },
  primaryButton: { minHeight: 54, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.sm, borderRadius: radii.md, backgroundColor: colors.accent },
  primaryButtonText: { ...type.button, color: colors.accentText },
  secondaryButton: { minHeight: 50, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.sm, borderRadius: radii.md, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface },
  secondaryButtonText: { ...type.button, color: colors.textPrimary },
  estimateNote: { ...type.caption, color: colors.textMuted, textAlign: 'center', lineHeight: 18 },
  sourceBlock: { gap: spacing.sm, paddingTop: spacing.sm, borderTopWidth: 1, borderTopColor: colors.border },
  sourceText: { ...type.caption, color: colors.textSecondary },
  sourceLink: { ...type.label, color: colors.accent, paddingVertical: spacing.xs },
  creditLink: { ...type.caption, color: colors.textSecondary, textDecorationLine: 'underline', paddingVertical: spacing.xs },
  emptyState: { alignItems: 'center', gap: spacing.sm, paddingVertical: spacing.xxl, paddingHorizontal: spacing.lg },
  emptyTitle: { ...type.subheading, color: colors.textPrimary, textAlign: 'center' },
  emptyCopy: { ...type.body, color: colors.textSecondary, textAlign: 'center', maxWidth: 420 },
});
