import { StyleSheet } from 'react-native';
import { colors, spacing, radii, type, elevation, MIN_TOUCH_TARGET } from '../theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingHorizontal: 14,
    paddingTop: spacing.xl,
    paddingBottom: 7,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  backButton: { width: 40, height: 40, borderRadius: radii.md, alignItems: 'center', justifyContent: 'center' },
  headerAvatar: {
    width: 36,
    height: 36,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerName: { ...type.subheading, flex: 1, fontSize: 16, lineHeight: 20, letterSpacing: -0.2 },
  planButton: { width: 40, height: 40, borderRadius: radii.md, alignItems: 'center', justifyContent: 'center' },
  planButtonText: { ...type.caption, color: colors.accent },
  safetyButton: { width: 40, height: 40, borderRadius: radii.md, alignItems: 'center', justifyContent: 'center' },
  errorBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
    backgroundColor: colors.dangerSurface,
    borderRadius: radii.md,
    padding: spacing.md,
    margin: spacing.md,
  },
  errorText: { ...type.body, color: colors.danger, flex: 1 },
  retryText: { ...type.button, color: colors.danger },
  hideoutList: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    gap: spacing.xs,
  },
  hideoutRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    padding: spacing.sm,
  },
  hideoutInfo: { flex: 1 },
  hideoutName: { ...type.body, color: colors.textPrimary, fontWeight: '700' },
  hideoutCoords: { ...type.caption },
  hideoutCoordsLink: { color: colors.accent, textDecorationLine: 'underline' },
  hideoutDelete: { padding: spacing.xs },
  messageList: { paddingHorizontal: 14, paddingVertical: 12, gap: 7, flexGrow: 1 },
  messageListEmpty: { justifyContent: 'center' },
  loadOlderButton: { alignSelf: 'center', minHeight: MIN_TOUCH_TARGET, justifyContent: 'center', paddingHorizontal: spacing.md },
  loadOlderText: { ...type.caption, color: colors.accent, fontWeight: '700' },
  chatEmpty: { alignItems: 'center', gap: spacing.sm, paddingHorizontal: spacing.xl, paddingVertical: spacing.xl },
  chatEmptyTitle: { ...type.subheading, color: colors.textPrimary, textAlign: 'center' },
  chatEmptyText: { ...type.caption, textAlign: 'center' },
  bubbleRow: { flexDirection: 'row', marginBottom: spacing.sm },
  bubbleRowMine: { justifyContent: 'flex-end' },
  bubbleRowTheirs: { justifyContent: 'flex-start' },
  bubbleColumn: { maxWidth: '80%' },
  bubble: { borderRadius: 10, paddingHorizontal: 11, paddingVertical: 9 },
  bubbleMine: { backgroundColor: colors.accent },
  bubbleTheirs: { backgroundColor: colors.surface },
  bubbleFailed: { opacity: 0.6, borderWidth: 1, borderColor: colors.danger },
  bubbleText: { ...type.body, color: colors.textPrimary },
  bubbleTextMine: { color: colors.accentText },
  bubbleTime: { ...type.caption, marginTop: spacing.xs },
  bubbleTimeMine: { color: colors.accentText, opacity: 0.7 },
  bubbleStatusCaption: { ...type.caption, textAlign: 'right', marginTop: spacing.xs },
  bubbleStatusCaptionFailed: {
    ...type.caption,
    color: colors.danger,
    fontWeight: '700',
    textAlign: 'right',
    marginTop: spacing.xs,
  },
  composer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
    paddingHorizontal: 12,
    paddingTop: 9,
    paddingBottom: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
  },
  composerInput: {
    flex: 1,
    minHeight: 44,
    maxHeight: 112,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    ...type.body,
    fontSize: 14,
    lineHeight: 20,
    color: colors.textPrimary,
  },
  sendButton: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendButtonPressed: { backgroundColor: colors.accentPressed },
  sendButtonDisabled: { opacity: 0.5 },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.55)', justifyContent: 'flex-end' },
  modalSheet: {
    backgroundColor: colors.background,
    borderTopLeftRadius: radii.xl,
    borderTopRightRadius: radii.xl,
    borderWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: 0,
    borderColor: colors.border,
    padding: spacing.lg,
    paddingBottom: spacing.xl,
  },
  modalHandle: {
    width: 40,
    height: 4,
    borderRadius: radii.pill,
    backgroundColor: colors.border,
    alignSelf: 'center',
    marginBottom: spacing.md,
  },
  modalHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.md, marginBottom: spacing.lg },
  modalHeaderCopy: { flex: 1, minWidth: 0 },
  modalTitle: { ...type.heading, textAlign: 'left', marginBottom: spacing.xs },
  modalSubtitle: { ...type.caption, textAlign: 'left', lineHeight: 19 },
  modalClose: {
    width: 40,
    height: 40,
    borderRadius: radii.md,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceRaised,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
  },
  modalInput: {
    minHeight: MIN_TOUCH_TARGET,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceRaised,
    borderRadius: radii.md,
    paddingHorizontal: spacing.md,
    marginBottom: spacing.md,
    ...type.body,
    color: colors.textPrimary,
  },
  modalSectionLabel: { ...type.label, marginBottom: spacing.sm },
  coordRow: { flexDirection: 'row', gap: spacing.sm },
  coordInput: { flex: 1, marginBottom: 0 },
  modalCaption: { ...type.caption, marginTop: spacing.sm, marginBottom: spacing.md },
  modalErrorBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
    backgroundColor: colors.dangerSurface,
    borderRadius: radii.md,
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  modalErrorText: { ...type.body, color: colors.danger, flex: 1 },
  modalDone: {
    minHeight: MIN_TOUCH_TARGET,
    backgroundColor: colors.accent,
    borderRadius: radii.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalDoneDisabled: { opacity: 0.5 },
  modalDoneText: { ...type.button, color: colors.accentText },
});
