import { StyleSheet } from 'react-native';
import { colors, spacing, radii, type, elevation, MIN_TOUCH_TARGET } from '../theme';

export const NAVIGATION_SUMMARY_BASE_HEIGHT = 104;

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  mapFill: { flex: 1 },
  map: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0 },
  hostFill: { flex: 1, padding: 0, backgroundColor: colors.background },
  searchSlot: {
    position: 'absolute',
    left: spacing.md,
    right: spacing.md,
    zIndex: 9,
  },
  mapActions: {
    position: 'absolute',
    right: spacing.md,
    zIndex: 10,
    gap: spacing.sm,
  },
  mapActionButton: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: colors.surfaceRaised,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOpacity: 0.35,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  mapActionButtonActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accent,
  },
  currentLocationMarker: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.accent,
    borderWidth: 3,
    borderColor: '#ffffff',
    ...elevation.raised,
  },
  nearbyCount: {
    position: 'absolute',
    left: spacing.lg,
    maxWidth: '72%',
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    ...elevation.raised,
  },
  nearbyCountText: { ...type.caption, color: colors.textSecondary, fontWeight: '700', flexShrink: 1 },
  hazardCardRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginTop: spacing.sm },
  hazardVoteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: radii.md,
    backgroundColor: colors.surfaceRaised,
  },
  hazardVoteText: { ...type.caption, color: colors.textPrimary, fontWeight: '700' },
  destinationCard: {
    position: 'absolute',
    left: spacing.md,
    right: spacing.md,
    gap: spacing.sm,
    padding: spacing.md,
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    backgroundColor: colors.background,
    ...elevation.raised,
  },
  destinationCardHead: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  destinationCardIcon: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.accentSoft,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
  },
  destinationCardCopy: { minWidth: 0, flex: 1 },
  destinationCardTitle: { ...type.subheading, color: colors.textPrimary, fontWeight: '800' },
  destinationCardCoords: { ...type.caption, color: colors.textMuted, marginTop: 2 },
  destinationCardDismiss: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceRaised,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
  },
  destinationCardEta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginTop: spacing.sm,
    paddingTop: spacing.sm,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
  },
  destinationCardEtaText: { ...type.caption, color: colors.textSecondary, fontWeight: '700' },
  destinationPrimaryAction: {
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    borderRadius: 14,
    backgroundColor: colors.accent,
  },
  destinationPrimaryTitle: { ...type.button, color: colors.accentText, lineHeight: 19 },
  destinationPrimarySubtitle: { ...type.caption, color: colors.accentText, opacity: 0.72, marginTop: 1 },
  navigationActions: {
    position: 'absolute',
    right: spacing.md,
    zIndex: 12,
    flexDirection: 'column',
    alignItems: 'center',
    gap: spacing.sm,
  },
  navigationActionButton: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: colors.surfaceRaised,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOpacity: 0.35,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  navigationActionButtonActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  navigationDestinationMarker: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.accent,
    borderWidth: 3,
    borderColor: colors.background,
    ...elevation.raised,
  },
  navigationBanner: {
    position: 'absolute',
    left: spacing.sm,
    right: spacing.sm,
    overflow: 'hidden',
    borderRadius: 18,
    backgroundColor: colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    ...elevation.raised,
  },
  navigationBannerMain: {
    minHeight: 116,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  navigationManeuver: {
    width: 70,
    height: 78,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navigationBannerCopy: { flex: 1, minWidth: 0 },
  navigationDistance: { color: colors.accent, fontSize: 39, lineHeight: 42, fontWeight: '800', letterSpacing: -0.9 },
  navigationInstruction: { ...type.body, color: colors.textPrimary, marginTop: 1, fontSize: 18, lineHeight: 21, fontWeight: '800' },
  navigationProviderInstruction: { ...type.caption, minWidth: 0, color: colors.textSecondary, marginTop: 4, fontSize: 13, lineHeight: 17, fontWeight: '600' },
  navigationNextPreview: {
    minHeight: 50,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: 14,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
    backgroundColor: colors.background,
  },
  navigationNextGlyph: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navigationNextLabel: { ...type.caption, color: colors.textMuted, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.7 },
  navigationNextInstruction: { ...type.body, color: colors.textSecondary, flex: 1, fontSize: 15, lineHeight: 20, fontWeight: '600' },
  navigationNoticeRow: {
    minHeight: 40,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
    backgroundColor: colors.dangerSurface,
  },
  navigationNotice: { ...type.caption, color: colors.textSecondary, flex: 1 },
  navigationEndButton: {
    width: MIN_TOUCH_TARGET,
    height: MIN_TOUCH_TARGET,
    borderRadius: MIN_TOUCH_TARGET / 2,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceRaised,
  },
  navigationSpeedBadge: {
    position: 'absolute',
    right: spacing.md,
    zIndex: 13,
    width: 76,
    height: 76,
    borderRadius: 38,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(13,21,26,0.94)',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.18)',
    ...elevation.raised,
  },
  navigationSpeedBadgeValue: {
    color: colors.textPrimary,
    fontSize: 30,
    lineHeight: 32,
    fontWeight: '800',
    letterSpacing: -0.8,
  },
  navigationSpeedBadgeUnit: {
    marginTop: 1,
    color: colors.textMuted,
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  navigationSummary: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    minHeight: NAVIGATION_SUMMARY_BASE_HEIGHT,
    paddingTop: 10,
    paddingHorizontal: spacing.lg,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: colors.surface,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    ...elevation.raised,
  },
  navigationSummaryHandle: {
    width: 46,
    height: 5,
    alignSelf: 'center',
    marginBottom: 10,
    borderRadius: 3,
    backgroundColor: colors.textMuted,
    opacity: 0.55,
  },
  navigationSummaryContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  navigationSummaryPrimary: { flex: 1.08, minWidth: 78 },
  navigationSummaryStat: { flex: 1, minWidth: 0, alignItems: 'center' },
  navigationSummaryDivider: { width: StyleSheet.hairlineWidth, height: 46, backgroundColor: colors.border },
  navigationArrival: { ...type.heading, color: colors.success, fontSize: 25, lineHeight: 30 },
  navigationSummaryValue: { ...type.heading, color: colors.textPrimary, fontSize: 21, lineHeight: 27, textAlign: 'center' },
  navigationSummaryLabel: { ...type.caption, color: colors.textMuted, marginTop: 2, textAlign: 'center', textTransform: 'uppercase' },
  rideBarSlot: { marginTop: 'auto', paddingHorizontal: spacing.lg, paddingBottom: spacing.lg },
  safetyBanner: {
    position: 'absolute', left: spacing.lg, right: spacing.lg,
    flexDirection: 'row', alignItems: 'center', gap: spacing.sm,
    padding: spacing.md, borderRadius: radii.lg,
    borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface,
    ...elevation.raised,
  },
  safetyBannerCopy: { flex: 1 },
  safetyBannerTitle: { ...type.label, color: colors.textPrimary },
  safetyBannerText: { ...type.caption, color: colors.textSecondary, marginTop: 2 },
  safetyEnableButton: { minHeight: 40, justifyContent: 'center', paddingHorizontal: spacing.md, borderRadius: radii.md, backgroundColor: colors.accent },
  safetyEnableText: { ...type.caption, color: colors.accentText, fontWeight: '800' },
});
