import { StyleSheet } from 'react-native';
import { colors, spacing, radii, type, MIN_TOUCH_TARGET } from '../theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  scroll: { width: '100%', maxWidth: 760, alignSelf: 'center', paddingHorizontal: spacing.md, paddingVertical: spacing.md, paddingTop: spacing.lg },
  profileCard: {
    minHeight: 100,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    backgroundColor: colors.surfaceRaised,
  },
  profileSaveStatus: { minHeight: 24, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginTop: -spacing.sm, marginBottom: spacing.sm, paddingHorizontal: spacing.xs },
  profileSavingText: { ...type.caption, color: colors.textSecondary },
  profileSaveError: { ...type.caption, color: colors.danger, flex: 1 },
  profileCopy: { flex: 1, minWidth: 0, gap: 3 },
  name: { ...type.subheading, color: colors.textPrimary, flexShrink: 1, fontSize: 17, lineHeight: 21 },
  handle: { ...type.caption, color: colors.textSecondary, flexShrink: 1, fontSize: 12, lineHeight: 16 },
  tierRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
    padding: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  tierRowSelected: { backgroundColor: colors.surfaceRaised },
  tierRowPressed: { opacity: 0.85 },
  tierRadio: {
    width: 22,
    height: 22,
    borderRadius: radii.pill,
    borderWidth: 2,
    borderColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  tierRadioDot: { width: 10, height: 10, borderRadius: radii.pill, backgroundColor: colors.accent },
  tierInfo: { flex: 1, gap: spacing.xs },
  tierName: { ...type.body, color: colors.textPrimary, fontWeight: '700', fontSize: 16 },
  tierBlurb: { ...type.caption },
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    minHeight: MIN_TOUCH_TARGET,
    paddingHorizontal: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  toggleIcon: { width: 20 },
  toggleInfo: { flex: 1, gap: spacing.xs, paddingVertical: spacing.sm },
  toggleLabel: { ...type.body, color: colors.textPrimary },
  toggleCaption: { ...type.caption },
  socialRow: { padding: spacing.md, gap: spacing.sm, borderBottomWidth: 1, borderBottomColor: colors.border },
  socialHeading: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  socialInput: { ...type.body, color: colors.textPrimary, minHeight: MIN_TOUCH_TARGET, backgroundColor: colors.surfaceRaised, borderRadius: radii.md, paddingHorizontal: spacing.md },
  socialError: { ...type.caption, color: colors.danger },
  visibilityRow: { flexDirection: 'row', gap: spacing.xs },
  visibilityChoice: { flex: 1, minHeight: 44, alignItems: 'center', justifyContent: 'center', borderRadius: radii.md, backgroundColor: colors.surfaceRaised },
  visibilityChoiceActive: { backgroundColor: colors.accent },
  visibilityText: { ...type.caption, fontSize: 11 },
  visibilityTextActive: { color: colors.accentText, fontWeight: '700' },
  aboutLabel: { ...type.body, color: colors.textPrimary },
  aboutValue: { ...type.caption },
  sessionRow: { minHeight: 64, flexDirection: 'row', alignItems: 'center', gap: spacing.md, padding: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.border },
  sessionInfo: { flex: 1, gap: spacing.xs },
  sessionRevoke: { minHeight: MIN_TOUCH_TARGET, justifyContent: 'center', paddingHorizontal: spacing.sm },
  sessionRevokeText: { ...type.button, color: colors.danger },
  sessionEmpty: { ...type.caption, padding: spacing.md },
  sessionLoading: { minHeight: 56, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.sm },
  sheetActionDisabled: { opacity: 0.55 },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.55)', justifyContent: 'flex-end' },
  modalSheet: {
    backgroundColor: colors.background,
    borderTopLeftRadius: radii.xl,
    borderTopRightRadius: radii.xl,
    padding: spacing.md,
    paddingBottom: spacing.xl,
    borderWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: 0,
    borderColor: colors.border,
  },
  modalHandle: {
    width: 40,
    height: 4,
    borderRadius: radii.pill,
    backgroundColor: colors.border,
    alignSelf: 'center',
    marginBottom: spacing.md,
  },
  modalHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.md, marginBottom: spacing.lg },
  modalHeaderCopy: { flex: 1, minWidth: 0 },
  modalTitle: { ...type.heading, textAlign: 'left', marginBottom: spacing.xs },
  modalSubtitle: { ...type.caption, textAlign: 'left', lineHeight: 19 },
  modalClose: {
    width: 40,
    height: 40,
    borderRadius: radii.md,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceRaised,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
  },
  avatarFamilyTabs: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: spacing.md,
    padding: 4,
    borderRadius: radii.md,
    backgroundColor: colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
  },
  avatarFamilyTab: {
    flex: 1,
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    borderRadius: radii.sm,
  },
  avatarFamilyTabActive: { backgroundColor: colors.accent },
  avatarFamilyTabText: { ...type.caption, color: colors.textSecondary, fontWeight: '700', fontSize: 10 },
  avatarFamilyTabTextActive: { color: colors.accentText },
  avatarPickerScroll: { maxHeight: 330 },
  avatarGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', rowGap: spacing.md, paddingBottom: spacing.xs },
  avatarGridItem: {
    width: '23%',
    minHeight: 86,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    paddingVertical: 7,
    borderRadius: radii.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  avatarGridItemSelected: {
    borderColor: colors.accent,
    backgroundColor: colors.surfaceRaised,
  },
  avatarGridLabel: { ...type.caption, color: colors.textSecondary, fontSize: 9, fontWeight: '700' },
  avatarCheck: { position: 'absolute', right: 3, top: 3 },
  modalDone: {
    minHeight: MIN_TOUCH_TARGET,
    backgroundColor: colors.accent,
    borderRadius: radii.md,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: spacing.lg,
  },
  modalDoneText: { ...type.button, color: colors.accentText },
  settingsGroup: { overflow: 'hidden', backgroundColor: colors.surfaceRaised, borderRadius: 8, borderWidth: StyleSheet.hairlineWidth, borderColor: colors.border },
  secondarySettingsGroup: { marginTop: 12 },
  signOutGroup: { marginTop: 12 },
  settingRow: { minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border },
  settingRowLast: { borderBottomWidth: 0 },
  settingRowPressed: { backgroundColor: colors.surface },
  settingRowIcon: { width: 20 },
  settingRowCopy: { flex: 1, minWidth: 0, paddingVertical: 7 },
  settingRowTitle: { ...type.body, color: colors.textPrimary, fontWeight: '500', fontSize: 14, lineHeight: 18 },
  settingRowSubtitle: { ...type.caption, color: colors.textSecondary, marginTop: 2, fontSize: 10 },
  settingRowValue: { ...type.caption, color: colors.textSecondary, fontWeight: '700', maxWidth: '34%', flexShrink: 1 },
  settingRowDanger: { color: colors.danger },
  aboutSummary: { padding: spacing.md, gap: 4 },
  aboutTitle: { ...type.subheading, color: colors.textPrimary },
  aboutSummaryValue: { ...type.caption, color: colors.textSecondary },
  settingsSheet: { width: '100%', maxHeight: '86%', backgroundColor: colors.background, borderTopLeftRadius: radii.xl, borderTopRightRadius: radii.xl, borderWidth: StyleSheet.hairlineWidth, borderBottomWidth: 0, borderColor: colors.border, padding: spacing.md },
  settingsSheetHeader: { minHeight: MIN_TOUCH_TARGET, flexDirection: 'row', alignItems: 'center', gap: spacing.md, marginBottom: spacing.sm },
  settingsSheetTitle: { ...type.heading, color: colors.textPrimary, flex: 1 },
  settingsSheetBody: { gap: spacing.md, paddingBottom: spacing.sm },
  settingsSheetSection: { overflow: 'hidden', borderWidth: StyleSheet.hairlineWidth, borderColor: colors.border, borderRadius: radii.lg, backgroundColor: colors.surface },
  sheetEyebrow: { ...type.label, color: colors.textMuted, paddingHorizontal: spacing.md, paddingTop: spacing.md, paddingBottom: spacing.xs },
  fieldLabel: { ...type.caption, color: colors.textSecondary, fontWeight: '700', paddingHorizontal: spacing.md, paddingTop: spacing.md },
  sheetInput: { ...type.body, color: colors.textPrimary, minHeight: MIN_TOUCH_TARGET, marginHorizontal: spacing.md, marginTop: spacing.xs, paddingHorizontal: spacing.md, borderWidth: StyleSheet.hairlineWidth, borderColor: colors.border, borderRadius: radii.md, backgroundColor: colors.background },
  sheetAvatarRow: { minHeight: 76, flexDirection: 'row', alignItems: 'center', gap: spacing.md, marginHorizontal: spacing.md, marginTop: spacing.xs, padding: spacing.sm, borderWidth: StyleSheet.hairlineWidth, borderColor: colors.border, borderRadius: radii.md, backgroundColor: colors.background },
  sheetAvatarCopy: { flex: 1, minWidth: 0 },
  sheetProfileName: { ...type.body, color: colors.textPrimary, fontWeight: '700' },
  sheetMeta: { ...type.caption, color: colors.textMuted, marginTop: 2 },
  sheetMetaBlock: { ...type.caption, color: colors.textMuted, margin: spacing.md },
  sheetSaveStatus: { minHeight: 28, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginHorizontal: spacing.md, marginBottom: spacing.md },
  sheetBodyCopy: { ...type.body, color: colors.textSecondary, padding: spacing.md, lineHeight: 22 },
  sheetNote: { padding: spacing.md, borderWidth: StyleSheet.hairlineWidth, borderColor: colors.border, borderRadius: radii.lg, backgroundColor: colors.surface },
  sheetNoteTitle: { ...type.body, color: colors.textPrimary, fontWeight: '700' },
  sheetNoteCopy: { ...type.caption, color: colors.textSecondary, marginTop: spacing.xs, lineHeight: 18 },
  sheetSecondaryAction: { minHeight: MIN_TOUCH_TARGET, alignItems: 'center', justifyContent: 'center', margin: spacing.md, borderWidth: StyleSheet.hairlineWidth, borderColor: colors.border, borderRadius: radii.md, backgroundColor: colors.surfaceRaised },
  sheetSecondaryActionStandalone: { minHeight: MIN_TOUCH_TARGET, alignItems: 'center', justifyContent: 'center', borderWidth: StyleSheet.hairlineWidth, borderColor: colors.border, borderRadius: radii.md, backgroundColor: colors.surfaceRaised },
  sheetSecondaryActionText: { ...type.button, color: colors.textPrimary },
  sheetDangerAction: { minHeight: MIN_TOUCH_TARGET, alignItems: 'center', justifyContent: 'center', marginHorizontal: spacing.md, marginBottom: spacing.md, borderWidth: StyleSheet.hairlineWidth, borderColor: colors.danger, borderRadius: radii.md, backgroundColor: colors.dangerSurface },
  sheetDangerActionText: { ...type.button, color: colors.danger },
  sheetLoader: { margin: spacing.lg },
  safetyRow: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.md, padding: spacing.md, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border },
  safetyCopyWrap: { flex: 1, minWidth: 0 },
  safetyTitle: { ...type.body, color: colors.textPrimary, fontWeight: '700' },
  safetyCopy: { ...type.caption, color: colors.textSecondary, marginTop: 2 },

});
