import * as React from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { TIER_RADIUS_MILES } from '@rider-comms/shared';
import type { ZoneTier } from '@rider-comms/shared';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import type { RootStackParamList } from '../navigation';
import { useSettings } from '../settings/SettingsContext';
import { colors, elevation, MIN_TOUCH_TARGET, radii, spacing, type } from '../theme';
type Props = NativeStackScreenProps<RootStackParamList, 'Subscription'>;
const PLANS: Array<{ tier: ZoneTier; name: string; text: string }> = [{ tier: 'free', name: 'Free', text: 'For riders immediately around you.' }, { tier: 'premium', name: 'Premium', text: 'For spread-out city and motorway groups.' }, { tier: 'premium_plus', name: 'Premium+', text: 'For touring and rural riding.' }];
export function SubscriptionScreen({ navigation }: Props): React.JSX.Element { const { zoneTier } = useSettings(); const insets = useSafeAreaInsets(); const unavailable = () => Alert.alert('Purchases aren’t live yet', 'App Store and Google Play products must be configured before purchases can be enabled.'); return <View style={styles.container}><View style={[styles.header, { paddingTop: insets.top + spacing.md }]}><Pressable onPress={() => navigation.goBack()} style={styles.back}><Ionicons name="chevron-back" size={24} color={colors.textPrimary}/></Pressable><Text style={styles.title}>Plans & billing</Text><View style={styles.back}/></View><ScrollView contentContainerStyle={styles.content}><Text style={styles.heading}>Choose your riding range</Text><Text style={styles.copy}>Both riders must be inside each other’s zone.</Text>{PLANS.map((plan) => { const current = plan.tier === zoneTier; return <View key={plan.tier} style={[styles.plan, current && styles.current, elevation.raised]}><View style={styles.planHead}><Text style={styles.planName}>{plan.name}</Text><Text style={styles.radius}>{TIER_RADIUS_MILES[plan.tier]} mi</Text></View><Text style={styles.copy}>{plan.text}</Text><Pressable disabled={current} onPress={unavailable} style={[styles.button, current && styles.disabled]}><Text style={styles.buttonText}>{current ? 'Current plan' : `Choose ${plan.name}`}</Text></Pressable></View>})}<Pressable style={styles.restore} onPress={unavailable}><Text style={styles.radius}>Restore purchases</Text></Pressable><Text style={styles.copy}>Prices and renewal terms will come directly from the App Store or Google Play.</Text></ScrollView></View>; }
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: colors.background }, header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: spacing.md, paddingBottom: spacing.md }, back: { width: MIN_TOUCH_TARGET, height: MIN_TOUCH_TARGET, alignItems: 'center', justifyContent: 'center' }, title: { ...type.heading, flex: 1, textAlign: 'center' }, content: { padding: spacing.lg, gap: spacing.md }, heading: { ...type.heading, textAlign: 'center' }, copy: { ...type.body, textAlign: 'center' }, plan: { backgroundColor: colors.surface, padding: spacing.lg, borderRadius: radii.lg, borderWidth: 1, borderColor: colors.border, gap: spacing.md }, current: { borderColor: colors.accent }, planHead: { flexDirection: 'row', justifyContent: 'space-between' }, planName: { ...type.heading }, radius: { ...type.label, color: colors.accent }, button: { minHeight: MIN_TOUCH_TARGET, backgroundColor: colors.accent, borderRadius: radii.lg, alignItems: 'center', justifyContent: 'center' }, disabled: { backgroundColor: colors.surfaceRaised }, buttonText: { ...type.button, color: colors.accentText }, restore: { minHeight: MIN_TOUCH_TARGET, alignItems: 'center', justifyContent: 'center' } });
